[package]
name = "space-bang-bang"
version = "0.1.0"
authors = ["fmdkdd <fmdkdd@gmail.com>"]
edition = "2018"

[dependencies]
glium = "0.23"
imgui = "0.0.22"
imgui-glium-renderer = "0.0.22"
imgui-winit-support = "0.0.22"
byteorder = "1.3.1"
