#!/usr/bin/env node

var argv = require('optimist')
	.usage('Usage: obo [file]')
	.argv;

var file = argv._[0];

if (file) {
  var fs = require('fs');
	var source = fs.readFileSync(file, 'utf8');
	run(source);
} else {
	stdin(run);
}

function run(source) {
	var obo = require('./interpreter');

  var AST;

  if (file.match(/.ast.js$/)) {
    with(require('./ASTnodes')) {
      AST = eval(source);
    }
  }
  else { // Assume .ast
    AST = JSON.parse(source);
  }

  var main = obo(AST);
  console.log(main.invoke('run'));
}

function stdin(callback) {
	var source = '';

	process.stdin.resume();
	process.stdin.setEncoding('utf8');

	process.stdin.on('data', function(chunk) {
		source += chunk;
	})
	process.stdin.on('end', function() {
		callback(source);
	})
}
