eval("var obj = {};"
+ "obj.obj = obj;"
+ "obj.self = obj;"
+ "function f() {"
+ "	console.log('deleting obj', delete obj);"
+ "}"
+ "function g() {"
+ "	console.log('deleting self', delete obj.self);"
+ "}"
+ "with (obj) {"
+ "	console.log(obj, obj.self);"
+ "	f();"
+ "	console.log(obj, obj.self);"
+ "}"
+ "console.log(obj, obj.self);");
