* MVP tasks
** Actual game loop
To prevent the player from droning the game and forcing them to be careful with
their moves, we can: add a timer, either continuous (as in QUELTRIS; more
stressful) or a discrete number of moves (more puzzle-oriented).

*** Timer
At min level, the timer should let you build without pressure.
Discrete level increase: timer drops more quickly, but timer reward stay the
same (maybe non-linear?  Could be a lookup table).

At high levels, you have no time to make non-optimal moves.

*** Pattern matching
Found [[https://chrisklimowski.com/projects/ogopogo/game/][Ogopogo]], good idea.  That game is all about matching palindromes of
colored squares.  No pressure, but the challenge comes from making enough long
palindromes to gain enough point to proceed.

Makes me think that in match-3 games, the skill you are developing is pattern
recognition of aligned colors, but to be better you also start to recognize
pattern that are almost-match-3, then almost+1, and patterns that can trigger
combos, etc.  Adding a timer just pressures you to pattern match and execute
quickly, mechanically even.

So, in Queltris, it's interesting to match Tetrominoes because it's unusual to
find these patterns.  But after a while, it becomes boring again because it's
always the same patterns.

Maybe a better game is one that gives you new patterns to learn to recognize,
and throw old ones.  "Do 10x T shapes", then "do 10x snakish things".  Patterns
should not be random.  They can also use more than one color.


** Pause screen
Blackout playfield to prevent cheating.

** Scoring
Multi-matches/combos can take time to setup.  Would be unfortunate to reward
fast single matches over elaborate setups.  The scoring should reward high-level
play accordingly.

Score increase at higher speed levels.

* Polish
** Add top line
Should have a hidden top line so when dropping we see squares from that line
fall instead of them popping after the fill holes animation and leaving a black
square in place

** Multiple modes
Tutorials: learn how to match shapes in few moves, how to turn one shape
into another without disturbing other pieces, without matching other things
around it, learn how to zap a piece from far away with quick rotate+direction,
how to setup combos...

Puzzle mode: rotation restriction instead of time, try to build the longest
chain, setup combos

Eliminate one color mode?  Maybe too random, but could trigger an unlock.

Time attack: best score in 3min?

Marathon: best score until dead?

** Color-blindness friendly
Shapes are easier to distinguish at a glance than colors anyway.

** Two-player modes
Competitive: send stones to other player.  Need a mechanism to get rid of stones

Cooperative: two crosshairs for the same (or slightly larger?) playfield.

** Palette swap
Cheap and easy to do.  Tetris does it on level change, could also be unlocks.

** Auto repeat inputs after delay?
Can't use the repeat of OS because that varies... but could do something
frame-based ala NES Tetris.

* Ideas
** Lock delay
Allow rotation for a small delay before checking for combos, ala Tetris.
Could allow to get out of tricky situation.  But that wouldn't let us set up
large combos I think.

** Patterns change over time
Breaks up the routine.  More things to juggle, makes the brain work.

Change should be signaled in advance (maybe after a set amount of matches for
this pattern?)

** Powerups
Filling a pattern unlocks a powerup.  Not many buttons on a NES pad
though... could use Select+A and Select+B but a bit clunky.

Potential powerups:
- clear stones
- freeze timer
- restore row

* Dev mode
** Draw mode
Where I can change the color of tiles using the mouse?  Though the NES doesn't
have a mouse...  So maybe just a switch?

Useful for testing setups.
